name: WurstCivTools
version: 1.0
author: [Maxopoly]
depend: [CivModCore]
softdepend: [Citadel,FactoryMod]
api-version: 1.16
main: com.github.maxopoly.WurstCivTools.WurstCivTools
commands:
permissions: